package com.sychev.mashaplus.utils


object Resources {

    object Strings {
        const val yarkost_blesk =
            "Яркость, блеск и целое музыкальное представление для вас и ваших гостей. Два блока — мировые хиты всех времен и любимые песни 90-ых в новой аранжировке от наших вокалистов и музыкантов, энергичные танцы и шикарные костюмы — вам точно нужно это прочувствовать!"
        const val vokalisty = "Вокалисты"
        const val vokalist = "Вокалист"
        const val kontakty = "Контакты"
        const val vokalisty_uppercase = "ВОКАЛИСТЫ"
        const val vokalistky = "Вокалистки"
        const val minimalniy_komplekt =
            "У вокалиста есть минимальный комплект оборудования, необходимый для подзвучивания"
        const val kolichestvo_blokov = "Количество блоков оговаривется заранее, возможны любые варианты"
        const val duet = "Дуэт"
        const val ogromnym_priemushestvom = "Огромным приемуществом нашего проекта является взаимозаменяемость"
        const val ostavit_zayavku = "Оставить заявку"
        const val otpravit = "Отправить"
        const val muzik_project =
            "MASHA PLUS – музыкальный проект, который реализует все форматы\n живых выступлений. От соло-вокалистов до кавер бэнда"
        const val sozday_meropriyatie = "Создай мероприятие по своим\nправилам"
        const val sostav_gruppy = "18  ВОКАЛИСТОВ  10  ИНСТРУМЕНТАЛИСТОВ  5  ЛЕТ"
        const val text_14 = "14"
        const val text_10 = "10"
        const val text_5 = "5"
        const val nashi_yslygi = "НАШИ УСЛУГИ"
        const val vacalnoye_show_uppercase = "ВОКАЛЬНОЕ ШОУ"
        const val vacalnoye_show = "Вокальное шоу"
        const val repertuar = "Репертуар"
        const val duet_uppercase = "ДУЭТ"
        const val ultima_band = "ULTIMA BAND"
        const val vokalistky_uppercase = "ВОКАЛИСТКИ"
        const val instrymentalisty = "Инструменталисты"
        const val let_text = "Лет"
        const val liza_ionovoa = "ЛИЗА\nИОНОВА"
        const val natalya_molodojen = "НАТАЛЬЯ\nМОЛОДОЖЁН"
        const val ula_lank = "ЮЛИЯ ЛАНК"
        const val jia = "ДЖИА"
        const val alina_viera = "АЛИНА\nВИЕРА"
        const val yla = "УЛА"
        const val elena = "ЕЛЕНА\nВЕСКРЕСЕНСКАЯ"
        const val milana = "МИЛАНА"
        const val alya = "АЛЯ"
        const val dora = "ДОРА"
        const val andrey = "АНДРЕЙ \nМАХОРИН"
        const val ilya = "ИЛЬЯ\nОКУЛОВ"
        const val ilya_star = "ИЛЬЯ \nСТАРЧИКОВ"
        const val marat = "МАРАТ"
        const val princip_constryktora =
            "Мы работаем по принципу конструктора, когда каждый\nзаказчик может составить дуэт из любых понравившихся\nвокалистов. А так же из вокалистов и инструменталистов "
        const val sasha_plus_alya = "САША + АЛЯ"
        const val lena_plus_liza = "ЛЕНА + ЛИЗА"
        const val ula_plus_yla = "ЮЛЯ + УЛА"
        const val ilya_plus_andrey = "ИЛЬЯ + АНДРЕЙ"
        const val dora_plus_alina = "ДОРА + АЛИНА"
        const val marat_plus_yla = "МАРАТ  + УЛА"
        const val milana_plus_jia = "МИЛАНА + ДЖИА"
        const val lena_plus_andrey = "ЛЕНА + АНДРЕЙ"
        const val alya_plus_diana = "АЛЯ + ДИАНА"
        const val spb = "г. Санкт - Петербург"
        const val ostavte_nomer = "Оставьте свой номер, создадим\nваше мероприятие вместе"
        const val bolshe_o_nas = "Больше о нас"
        const val vvedite_nomer_telefona_hint = "Введите номер телефона"
        const val jiviye_vystuplenya = "ЖИВЫЕ ВЫСТУПЛЕНИЯ"
        const val repertuar_uppercase = "РЕПЕРТУАР"
        const val tseni = "ЦЕНЫ"
        const val vajniye_voprosy = "ВАЖНЫЕ ВОПРОСЫ"
        const val created_by1 =
            "Музыкальный проект был создан 5 лет назад "
        const val created_by2 = "Марией Борониной"
        const val created_by3 = " - певицей, педагогом по эстрадному вокалу, бэк - вокалисткой "
        const val created_by4 = "Татьяны Булановой"
        const val bak_vocalistka = "Бэк-вокалистка: "
        const val bak_vocalistka_desc =
            "Татьяны Булановой, Федора Чистякова и гр. “Ноль”, гр. “КАФЕ”, \"SPb PINK FLOYD show\", “Братья Жемчужные” и др"
        const val studio_bak_vocal = "Студийный бэк вокал: "
        const val studio_bak_vocal_desc = "Александр Розенбаум, \"Тараканы\", \"Король и шут\", Юлия Михальчик."
        const val bolee_ten = "Более 10 лет "
        const val bolee_ten_desc =
            "работы в production studion на радиостанциях: \" Русское радио\", \"Эрмитаж\", \"Эльдорадио\", \"Европа плюс\", \"Радио Модерн\", \"Радио Шансон\""
        const val partners_titple = "ПОДДЕРЖИВАЕМ СОТРУДНИЧЕСТВО С РЕСТОРАНАМИ УЖЕ НЕСКОЛЬКО ЛЕТ:"
    }

    object Images {
        const val vocal_show = "/vocal_show.png"
        const val masha_logo = "/masha_logo.png"
        const val main_photo = "/main_photo.png"
        const val two_girls = "/two_girls.png"
        const val three_girls = "/three_girls.png"
        const val one_girl = "/one_girl.png"
        const val band = "/band.png"
        const val ula_silhouette = "/ula_silhouette.png"
        const val tanya_silhouette = "/tanya_silhouette.png"
        const val sasha_silhouette = "/sasha_silhouette.png"
        const val liza_silhouette = "/liza_silhouette.png"
        const val devochka_left = "/devochka_left.png"
        const val devochka_right = "/devochka_right.png"
        const val carousel_girl_1 = "/kto_ty.png"
        const val carousel_girl_2 = "/empty_eyes.png"
        const val carousel_girl_3 = "/paradise.png"
        const val carousel_girl_4 = "/ya_eto_ya.png"
        const val clyaksa1 = "/clyaksa.png"
        const val liza_vok = "/liza_vok.png"
        const val yla_vok = "/yla_vok.png"
        const val ula_vok = "/ula_vok.png"
        const val natalya_vok = "/natalya_vok.png"
        const val milana_vok = "/milana_vok.png"
        const val elena_vok = "/elena_vok.png"
        const val dora_vok = "/dora_vok.png"
        const val alya_vok = "/alya_vok.png"
        const val alina_vok = "/alina_vok.png"
        const val djia_vok = "/djia_vok.png"
        const val andrey_vok = "/andrey_vok.png"
        const val ilya_vok = "/ilya_vok.png"
        const val ilay_star_vok = "/ilya_starchikov_vok.png"
        const val marat_vok = "/marat_vok.png"
        const val clyaksa_2 = "/clyaksa_2.png"
        const val arrow_left = "/arrow_left.png"
        const val arrow_right = "/arrow_right.png"
        const val ic_phone = "/ic_phone.png"
        const val maria_boronina = "/maria_boronina.png"
        const val partner_bahroma_logo = "/partner_bahroma_logo.png"
        const val partner_feromon_logo = "/partner_feromon_logo.png"
        const val partner_grill_house_logo = "/partner_grill_house_logo.png"
        const val partner_hochy_harcho_logo = "/partner_hachy_harcho_logo.png"
        const val partner_kind_gruzin_logo = "/partner_kind_gruzin_logo.png"
        const val partner_mamaliga_logo = "/partner_mamaliga_logo.png"
        const val partner_peperoni_logo = "/partner_peperoni_logo.png"
        const val partner_vse_horosho_logo = "/partner_vse_horosho_logo.png"
    }

}